theme = "blowfish"
baseURL = "https://bochap.com/"
defaultContentLanguage = "en"
enableRobotsTXT = true
paginate = 18
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true
googleAnalytics = "G-SY7QKK17CP"

[params]
author = { name = "Darren Seet", image = "img/avatar.png", headline = "Sr Software Engineer", bio = "Senior Software Engineer", links = [ { linkedin = "https://linkedin.com/in/bochap" }, { github = "https://github.com/bochap" }, { medium = "https://medium.com/@bochap" } ] }

[imaging]
anchor = "Center"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[related]
threshold = 1
includeNewer = true
toLower = true
indices = [ { name = "tags", weight = 100 }, { name = "categories", weight = 100 }, { name = "series", weight = 50 }, { name = "authors", weight = 10 }, { name = "date", weight = 0 }, { applyFilter = true, name = "fragmentrefs", type = "fragments", weight = 10 } ]
