# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
baseURL = "https://bochap.com/"
defaultContentLanguage = "en"
# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles
enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false

enableEmoji = true
googleAnalytics = "G-SY7QKK17CP"

[pagination]
  pagerSize = 100

[params]
author = { name = "Darren Seet", image = "img/avatar.png", headline = "Sr Software Engineer", bio = "Senior Software Engineer", links = [ { linkedin = "https://linkedin.com/in/bochap" }, { github = "https://github.com/bochap" }, { medium = "https://medium.com/@bochap" } ] }

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
    priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 1
  includeNewer = true
  toLower = true

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 10

    [[related.indices]]
        name = "date"
        weight = 0

    [[related.indices]]
      applyFilter = true
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10