[[main]]
none = "none"

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "IyZQpEX03J"
weight = 20

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 30
